//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtsDBEntities : DbContext
    {
        public ArtsDBEntities()
            : base("name=ArtsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ArtistPost> tbl_ArtistPost { get; set; }
        public virtual DbSet<tbl_ArtistPostDetail> tbl_ArtistPostDetail { get; set; }
        public virtual DbSet<tbl_Auction> tbl_Auction { get; set; }
        public virtual DbSet<tbl_AuctionDetial> tbl_AuctionDetial { get; set; }
        public virtual DbSet<tbl_AuctionOrder> tbl_AuctionOrder { get; set; }
        public virtual DbSet<tbl_Bid> tbl_Bid { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_Complaint> tbl_Complaint { get; set; }
        public virtual DbSet<tbl_Follow> tbl_Follow { get; set; }
        public virtual DbSet<tbl_Item> tbl_Item { get; set; }
        public virtual DbSet<tbl_ItemDetail> tbl_ItemDetail { get; set; }
        public virtual DbSet<tbl_ItemNotification> tbl_ItemNotification { get; set; }
        public virtual DbSet<tbl_ItemOrder> tbl_ItemOrder { get; set; }
        public virtual DbSet<tbl_PostNotification> tbl_PostNotification { get; set; }
        public virtual DbSet<tbl_Shipping> tbl_Shipping { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_UserDetail> tbl_UserDetail { get; set; }
    }
}
