//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Shipping
    {
        public int ShippingId { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public string ShippingTotal { get; set; }
        public int UserId { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
    
        public virtual tbl_Item tbl_Item { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
