//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuctionDetial
    {
        public int AuctionId { get; set; }
        public int AuctionDetailId { get; set; }
        public string AuctionImage { get; set; }
    
        public virtual tbl_Auction tbl_Auction { get; set; }
    }
}
