//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Auction()
        {
            this.tbl_AuctionDetial = new HashSet<tbl_AuctionDetial>();
            this.tbl_AuctionOrder = new HashSet<tbl_AuctionOrder>();
            this.tbl_Bid = new HashSet<tbl_Bid>();
        }
    
        public int AuctionId { get; set; }
        public string AuctionName { get; set; }
        public System.DateTime AuctionLastDate { get; set; }
        public int UserId { get; set; }
        public string AuctionDesc { get; set; }
        public string StartingBid { get; set; }
        public string IsApproved { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AuctionDetial> tbl_AuctionDetial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AuctionOrder> tbl_AuctionOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bid> tbl_Bid { get; set; }
    }
}
