//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testmodek
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemOrder
    {
        public int tbl_Item_ItemId { get; set; }
        public int tbl_User_UserId { get; set; }
        public int Quantity { get; set; }
        public int OrderId { get; set; }
    
        public virtual tbl_Item tbl_Item { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
