//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testmodek
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemNotification
    {
        public int NotificationId { get; set; }
        public int BuyerId { get; set; }
        public int SellerId { get; set; }
        public int ItemId { get; set; }
        public Nullable<System.DateTime> ViewTime { get; set; }
    
        public virtual tbl_Item tbl_Item { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
    }
}
