//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuctionOrder
    {
        public int AuctionOrderId { get; set; }
        public System.DateTime AuctionOrderDate { get; set; }
        public int AuctionItemId { get; set; }
        public string AuctionOrderTotal { get; set; }
        public int UserId { get; set; }
    
        public virtual tbl_Auction tbl_Auction { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
